In [22]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

#df_base = pd.read_csv("data/^990100-USD-STRD (1).csv")
df_base = pd.read_csv("data/^SPX (1).csv")
# 3USL.L.csv
#df = pd.read_csv("data/3USL.L.csv") # 3x sp500
# DBPG.DE.csv
df = pd.read_csv("data/DBPG.DE.csv") # 2x sp500

df = df.dropna(axis=0)

df["Date"] = pd.to_datetime(df["Date"])
#df = df[df["Date"] >= "2016-10-08"]
#df.to_csv("data/SP500_Tobi_30j.csv")

df

,Date,Open,High,Low,Close,Adj Close,Volume
1666,2016-10-10,37.880001,38.279999,37.820000,38.279999,38.279999,1104.0
1667,2016-10-11,38.169998,38.230000,37.650002,37.650002,37.650002,2489.0
1668,2016-10-12,37.540001,37.779999,37.500000,37.779999,37.779999,190.0
1669,2016-10-13,37.240002,37.240002,36.869999,37.169998,37.169998,6366.0
1670,2016-10-14,37.529999,37.770000,37.529999,37.770000,37.770000,17.0
...,...,...,...,...,...,...,...
3558,2024-03-18,169.979996,172.720001,169.539993,172.039993,172.039993,19309.0
3559,2024-03-19,171.360001,172.380005,170.039993,172.380005,172.380005,6620.0
3560,2024-03-20,173.020004,173.960007,173.000000,173.300003,173.300003,2882.0
3561,2024-03-21,177.320007,178.919998,176.600006,178.660004,178.660004,6407.0
3562,2024-03-22,178.339996,178.839996,177.539993,177.639999,177.639999,6622.0

In [35]:
def calc_returns(prices):
    returns = [0]
    counter = len(prices)
    for i in range(1, counter):
        ret = prices[i] / prices[i-1] - 1
        returns.append(ret)
    return returns

def x_to_y(x, y):
    x2y = []
    for i in range(len(x)):
        x2y.append(y[i] / x[i] - 1)
    return x2y


df["daily_movement_1x"] = calc_returns(df["Adj Close"].to_list())
df["daily_movement_2x"] = df["daily_movement_1x"] * 2
df["daily_movement_3x"] = df["daily_movement_1x"] * 3

df["open_to_low_1x"] = x_to_y(df["Open"].to_list(), df["Low"].to_list())
df["open_to_high_1x"] = x_to_y(df["Open"].to_list(), df["High"].to_list())
df["adj_close_to_open_1x"] = x_to_y(df["Adj Close"].to_list(), df["Open"].to_list())
df["open_to_low_2x"] = df["open_to_low_1x"] * 2
df["open_to_high_2x"] = df["open_to_high_1x"] * 2
df["adj_close_to_open_2x"] = df["adj_close_to_open_1x"] * 2
df["open_to_low_3x"] = df["open_to_low_1x"] * 3
df["open_to_high_3x"] = df["open_to_high_1x"] * 3
df["adj_close_to_open_3x"] = df["adj_close_to_open_1x"] * 3

df

,Date,Open,High,Low,Close,Adj Close,Volume,daily_movement_1x,daily_movement_2x,daily_movement_3x,open_to_low_1x,open_to_high_1x,adj_close_to_open_1x,open_to_low_2x,open_to_high_2x,adj_close_to_open_2x,open_to_low_3x,open_to_high_3x,adj_close_to_open_3x,cum_return_1x,cum_return_2x,cum_return_3x,adj_close_2x,adj_close_3x,adj_close_1x,mavg_200_adj_close_1x,mavg_200_adj_close_2x,mavg_200_adj_close_3x,mavg_100_adj_close_1x,mavg_100_adj_close_2x,mavg_100_adj_close_3x
1867,2017-07-24,47.849998,47.849998,47.740002,47.740002,47.740002,25.0,0.000000,0.000000,0.000000,-0.002299,0.000000,0.002304,-0.004598,0.000000,0.004608,-0.006896,0.000000,0.006912,1.247127,1.520896,1.813997,58.219896,69.439819,47.740002,45.08275,52.704690,61.073604,47.6974,58.381629,70.211665
1868,2017-07-25,47.799999,48.119999,47.799999,48.119999,48.119999,312.0,0.007960,0.015919,0.023879,0.000000,0.006695,-0.006650,0.000000,0.013389,-0.013300,0.000000,0.020084,-0.019950,1.257053,1.545108,1.857314,59.146724,71.097984,48.119999,45.13005,52.804390,61.229403,47.6937,58.367083,70.175396
1869,2017-07-26,48.110001,48.290001,48.110001,48.189999,48.189999,72.0,0.001455,0.002909,0.004364,0.000000,0.003741,-0.001660,0.000000,0.007483,-0.003320,0.000000,0.011224,-0.004980,1.258882,1.549603,1.865420,59.318805,71.408262,48.189999,45.18240,52.915024,61.402943,47.6804,58.328564,70.094656
1870,2017-07-27,47.880001,48.189999,47.830002,48.189999,48.189999,224.0,0.000000,0.000000,0.000000,-0.001044,0.006474,-0.006433,-0.002089,0.012949,-0.012866,-0.003133,0.019423,-0.019298,1.258882,1.549603,1.865420,59.318805,71.408262,48.189999,45.23445,53.025239,61.576149,47.6695,58.296097,70.025184
1871,2017-07-28,47.490002,47.570000,47.299999,47.299999,47.299999,949.0,-0.018469,-0.036937,-0.055406,-0.004001,0.001685,0.004017,-0.008002,0.003369,0.008034,-0.012003,0.005054,0.012051,1.235632,1.492365,1.762065,57.127739,67.451838,47.299999,45.28955,53.141474,61.758261,47.6630,58.274802,69.976699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3558,2024-03-18,169.979996,172.720001,169.539993,172.039993,172.039993,19309.0,0.020645,0.041291,0.061936,-0.002589,0.016120,-0.011974,-0.005177,0.032239,-0.023948,-0.007766,0.048359,-0.035922,4.494253,8.819471,7.128244,337.609342,272.869164,172.039993,139.11470,226.283216,155.138489,147.8882,253.878906,182.373311
3559,2024-03-19,171.360001,172.380005,170.039993,172.380005,172.380005,6620.0,0.001976,0.003953,0.005929,-0.007703,0.005952,-0.005917,-0.015406,0.011905,-0.011834,-0.023109,0.017857,-0.017752,4.503135,8.854332,7.170508,338.943813,274.487023,172.380005,139.35060,227.055385,155.932846,148.4064,255.582113,184.129427
3560,2024-03-20,173.020004,173.960007,173.000000,173.300003,173.300003,2882.0,0.005337,0.010674,0.016011,-0.000116,0.005433,-0.001616,-0.000231,0.010866,-0.003231,-0.000347,0.016299,-0.004847,4.527168,8.948844,7.285315,342.561723,278.881862,173.300003,139.59180,227.844790,156.745152,148.9554,257.374919,185.968221
3561,2024-03-21,177.320007,178.919998,176.600006,178.660004,178.660004,6407.0,0.030929,0.061858,0.092787,-0.004060,0.009023,-0.007500,-0.008121,0.018046,-0.015001,-0.012181,0.027070,-0.022501,4.667189,9.502402,7.961299,363.751926,304.758499,178.660004,139.83170,228.635074,157.563460,149.5282,259.243590,187.884745
3562,2024-03-22,178.339996,178.839996,177.539993,177.639999,177.639999,6622.0,-0.005709,-0.011418,-0.017128,-0.004486,0.002804,0.003941,-0.008972,0.005607,0.007881,-0.013457,0.008411,0.011822,4.640543,9.393900,7.824941,359.598464,299.538721,177.639999,140.09510,229.521591,158.502049,150.1536,261.321478,190.057780

In [36]:
# cum returns
def cum_returns(returns):
    cum_returns = [1]
    counter = len(returns)
    for i in range(1, counter):
        ret = (returns[i] + 1) * cum_returns[i-1]
        cum_returns.append(ret)
    return cum_returns

df["cum_return_1x"] = cum_returns(df["daily_movement_1x"].to_list())
df["cum_return_2x"] = cum_returns(df["daily_movement_2x"].to_list())
df["cum_return_3x"] = cum_returns(df["daily_movement_3x"].to_list())
df

,Date,Open,High,Low,Close,Adj Close,Volume,daily_movement_1x,daily_movement_2x,daily_movement_3x,open_to_low_1x,open_to_high_1x,adj_close_to_open_1x,open_to_low_2x,open_to_high_2x,adj_close_to_open_2x,open_to_low_3x,open_to_high_3x,adj_close_to_open_3x,cum_return_1x,cum_return_2x,cum_return_3x,adj_close_2x,adj_close_3x,adj_close_1x,mavg_200_adj_close_1x,mavg_200_adj_close_2x,mavg_200_adj_close_3x,mavg_100_adj_close_1x,mavg_100_adj_close_2x,mavg_100_adj_close_3x
1867,2017-07-24,47.849998,47.849998,47.740002,47.740002,47.740002,25.0,0.000000,0.000000,0.000000,-0.002299,0.000000,0.002304,-0.004598,0.000000,0.004608,-0.006896,0.000000,0.006912,1.000000,1.000000,1.000000,58.219896,69.439819,47.740002,45.08275,52.704690,61.073604,47.6974,58.381629,70.211665
1868,2017-07-25,47.799999,48.119999,47.799999,48.119999,48.119999,312.0,0.007960,0.015919,0.023879,0.000000,0.006695,-0.006650,0.000000,0.013389,-0.013300,0.000000,0.020084,-0.019950,1.007960,1.015919,1.023879,59.146724,71.097984,48.119999,45.13005,52.804390,61.229403,47.6937,58.367083,70.175396
1869,2017-07-26,48.110001,48.290001,48.110001,48.189999,48.189999,72.0,0.001455,0.002909,0.004364,0.000000,0.003741,-0.001660,0.000000,0.007483,-0.003320,0.000000,0.011224,-0.004980,1.009426,1.018875,1.028347,59.318805,71.408262,48.189999,45.18240,52.915024,61.402943,47.6804,58.328564,70.094656
1870,2017-07-27,47.880001,48.189999,47.830002,48.189999,48.189999,224.0,0.000000,0.000000,0.000000,-0.001044,0.006474,-0.006433,-0.002089,0.012949,-0.012866,-0.003133,0.019423,-0.019298,1.009426,1.018875,1.028347,59.318805,71.408262,48.189999,45.23445,53.025239,61.576149,47.6695,58.296097,70.025184
1871,2017-07-28,47.490002,47.570000,47.299999,47.299999,47.299999,949.0,-0.018469,-0.036937,-0.055406,-0.004001,0.001685,0.004017,-0.008002,0.003369,0.008034,-0.012003,0.005054,0.012051,0.990783,0.981241,0.971371,57.127739,67.451838,47.299999,45.28955,53.141474,61.758261,47.6630,58.274802,69.976699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3558,2024-03-18,169.979996,172.720001,169.539993,172.039993,172.039993,19309.0,0.020645,0.041291,0.061936,-0.002589,0.016120,-0.011974,-0.005177,0.032239,-0.023948,-0.007766,0.048359,-0.035922,3.603686,5.798865,3.929578,337.609342,272.869164,172.039993,139.11470,226.283216,155.138489,147.8882,253.878906,182.373311
3559,2024-03-19,171.360001,172.380005,170.039993,172.380005,172.380005,6620.0,0.001976,0.003953,0.005929,-0.007703,0.005952,-0.005917,-0.015406,0.011905,-0.011834,-0.023109,0.017857,-0.017752,3.610808,5.821787,3.952876,338.943813,274.487023,172.380005,139.35060,227.055385,155.932846,148.4064,255.582113,184.129427
3560,2024-03-20,173.020004,173.960007,173.000000,173.300003,173.300003,2882.0,0.005337,0.010674,0.016011,-0.000116,0.005433,-0.001616,-0.000231,0.010866,-0.003231,-0.000347,0.016299,-0.004847,3.630080,5.883929,4.016166,342.561723,278.881862,173.300003,139.59180,227.844790,156.745152,148.9554,257.374919,185.968221
3561,2024-03-21,177.320007,178.919998,176.600006,178.660004,178.660004,6407.0,0.030929,0.061858,0.092787,-0.004060,0.009023,-0.007500,-0.008121,0.018046,-0.015001,-0.012181,0.027070,-0.022501,3.742354,6.247897,4.388815,363.751926,304.758499,178.660004,139.83170,228.635074,157.563460,149.5282,259.243590,187.884745
3562,2024-03-22,178.339996,178.839996,177.539993,177.639999,177.639999,6622.0,-0.005709,-0.011418,-0.017128,-0.004486,0.002804,0.003941,-0.008972,0.005607,0.007881,-0.013457,0.008411,0.011822,3.720989,6.176556,4.313645,359.598464,299.538721,177.639999,140.09510,229.521591,158.502049,150.1536,261.321478,190.057780

In [462]:
# visual
import plotly.express as px
import chart_studio.plotly as py
import plotly.graph_objects as go
#df[["Date", "cum_return", "cum_return_2x", "cum_return_3x"]].set_index("Date").plot()


fig = px.line(df, x="Date", y=["cum_return", "cum_return_2x", "cum_return_3x"])
fig.write_html('figures/first_figure.html', auto_open=True)

In [37]:
# adj close
df["adj_close_2x"] = df["cum_return_2x"] * df["Adj Close"].to_list()[0]
df["adj_close_3x"] = df["cum_return_3x"] * df["Adj Close"].to_list()[0]
df["adj_close_1x"] = df["cum_return_1x"] * df["Adj Close"].to_list()[0]
df

,Date,Open,High,Low,Close,Adj Close,Volume,daily_movement_1x,daily_movement_2x,daily_movement_3x,open_to_low_1x,open_to_high_1x,adj_close_to_open_1x,open_to_low_2x,open_to_high_2x,adj_close_to_open_2x,open_to_low_3x,open_to_high_3x,adj_close_to_open_3x,cum_return_1x,cum_return_2x,cum_return_3x,adj_close_2x,adj_close_3x,adj_close_1x,mavg_200_adj_close_1x,mavg_200_adj_close_2x,mavg_200_adj_close_3x,mavg_100_adj_close_1x,mavg_100_adj_close_2x,mavg_100_adj_close_3x
1867,2017-07-24,47.849998,47.849998,47.740002,47.740002,47.740002,25.0,0.000000,0.000000,0.000000,-0.002299,0.000000,0.002304,-0.004598,0.000000,0.004608,-0.006896,0.000000,0.006912,1.000000,1.000000,1.000000,47.740002,47.740002,47.740002,45.08275,52.704690,61.073604,47.6974,58.381629,70.211665
1868,2017-07-25,47.799999,48.119999,47.799999,48.119999,48.119999,312.0,0.007960,0.015919,0.023879,0.000000,0.006695,-0.006650,0.000000,0.013389,-0.013300,0.000000,0.020084,-0.019950,1.007960,1.015919,1.023879,48.499996,48.879993,48.119999,45.13005,52.804390,61.229403,47.6937,58.367083,70.175396
1869,2017-07-26,48.110001,48.290001,48.110001,48.189999,48.189999,72.0,0.001455,0.002909,0.004364,0.000000,0.003741,-0.001660,0.000000,0.007483,-0.003320,0.000000,0.011224,-0.004980,1.009426,1.018875,1.028347,48.641102,49.093310,48.189999,45.18240,52.915024,61.402943,47.6804,58.328564,70.094656
1870,2017-07-27,47.880001,48.189999,47.830002,48.189999,48.189999,224.0,0.000000,0.000000,0.000000,-0.001044,0.006474,-0.006433,-0.002089,0.012949,-0.012866,-0.003133,0.019423,-0.019298,1.009426,1.018875,1.028347,48.641102,49.093310,48.189999,45.23445,53.025239,61.576149,47.6695,58.296097,70.025184
1871,2017-07-28,47.490002,47.570000,47.299999,47.299999,47.299999,949.0,-0.018469,-0.036937,-0.055406,-0.004001,0.001685,0.004017,-0.008002,0.003369,0.008034,-0.012003,0.005054,0.012051,0.990783,0.981241,0.971371,46.844439,46.373261,47.299999,45.28955,53.141474,61.758261,47.6630,58.274802,69.976699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3558,2024-03-18,169.979996,172.720001,169.539993,172.039993,172.039993,19309.0,0.020645,0.041291,0.061936,-0.002589,0.016120,-0.011974,-0.005177,0.032239,-0.023948,-0.007766,0.048359,-0.035922,3.603686,5.798865,3.929578,276.837847,187.598046,172.039993,139.11470,226.283216,155.138489,147.8882,253.878906,182.373311
3559,2024-03-19,171.360001,172.380005,170.039993,172.380005,172.380005,6620.0,0.001976,0.003953,0.005929,-0.007703,0.005952,-0.005917,-0.015406,0.011905,-0.011834,-0.023109,0.017857,-0.017752,3.610808,5.821787,3.952876,277.932106,188.710327,172.380005,139.35060,227.055385,155.932846,148.4064,255.582113,184.129427
3560,2024-03-20,173.020004,173.960007,173.000000,173.300003,173.300003,2882.0,0.005337,0.010674,0.016011,-0.000116,0.005433,-0.001616,-0.000231,0.010866,-0.003231,-0.000347,0.016299,-0.004847,3.630080,5.883929,4.016166,280.898772,191.731787,173.300003,139.59180,227.844790,156.745152,148.9554,257.374919,185.968221
3561,2024-03-21,177.320007,178.919998,176.600006,178.660004,178.660004,6407.0,0.030929,0.061858,0.092787,-0.004060,0.009023,-0.007500,-0.008121,0.018046,-0.015001,-0.012181,0.027070,-0.022501,3.742354,6.247897,4.388815,298.274626,209.522022,178.660004,139.83170,228.635074,157.563460,149.5282,259.243590,187.884745
3562,2024-03-22,178.339996,178.839996,177.539993,177.639999,177.639999,6622.0,-0.005709,-0.011418,-0.017128,-0.004486,0.002804,0.003941,-0.008972,0.005607,0.007881,-0.013457,0.008411,0.011822,3.720989,6.176556,4.313645,294.868809,205.933415,177.639999,140.09510,229.521591,158.502049,150.1536,261.321478,190.057780

In [ ]:
# visual
import plotly.express as px
import chart_studio.plotly as py
import plotly.graph_objects as go

fig = px.line(df, x="Date", y=["adj_close", "adj_close_2x", "adj_close_3x"])
fig.write_html('figures/first_figure0.html', auto_open=True)

In [38]:
# moving average
from statistics import mean

def moving_average(data, days):
    avg = [np.NaN] * days
    data = data.to_list()
    
    for i in range(days, len(data)):
        subset = data[i-days:i]
        avg.append(mean(subset))

    return avg

#df["mavg_300_adj_close"] = moving_average(df.adj_close, 300)
#df["mavg_300_adj_close_2x"] = moving_average(df.adj_close_2x, 300)
#df["mavg_300_adj_close_3x"] = moving_average(df.adj_close_3x, 300)
df["mavg_200_adj_close_1x"] = moving_average(df.adj_close_1x, 200)
df["mavg_200_adj_close_2x"] = moving_average(df.adj_close_2x, 200)
df["mavg_200_adj_close_3x"] = moving_average(df.adj_close_3x, 200)
df["mavg_100_adj_close_1x"] = moving_average(df.adj_close_1x, 100)
df["mavg_100_adj_close_2x"] = moving_average(df.adj_close_2x, 100)
df["mavg_100_adj_close_3x"] = moving_average(df.adj_close_3x, 100)
df.dropna(axis=0)

,Date,Open,High,Low,Close,Adj Close,Volume,daily_movement_1x,daily_movement_2x,daily_movement_3x,open_to_low_1x,open_to_high_1x,adj_close_to_open_1x,open_to_low_2x,open_to_high_2x,adj_close_to_open_2x,open_to_low_3x,open_to_high_3x,adj_close_to_open_3x,cum_return_1x,cum_return_2x,cum_return_3x,adj_close_2x,adj_close_3x,adj_close_1x,mavg_200_adj_close_1x,mavg_200_adj_close_2x,mavg_200_adj_close_3x,mavg_100_adj_close_1x,mavg_100_adj_close_2x,mavg_100_adj_close_3x
2067,2018-05-08,53.930000,54.189999,53.669998,54.119999,54.119999,5818.0,-0.000185,-0.000370,-0.000554,-0.004821,0.004821,-0.003511,-0.009642,0.009642,-0.007021,-0.014463,0.014463,-0.010532,1.133640,1.206356,1.202776,57.591429,57.420513,54.119999,52.045675,55.898706,59.120453,54.64045,60.707018,65.609295
2068,2018-05-09,54.700001,54.779999,54.490002,54.490002,54.490002,7501.0,0.006837,0.013673,0.020510,-0.003839,0.001462,0.003854,-0.007678,0.002925,0.007708,-0.011517,0.004387,0.011562,1.141391,1.222851,1.227445,58.378901,58.598216,54.490002,52.077575,55.947963,59.168856,54.63600,60.665645,65.492219
2069,2018-05-10,55.400002,55.869999,55.209999,55.869999,55.869999,5370.0,0.025326,0.050651,0.075977,-0.003430,0.008484,-0.008412,-0.006859,0.016967,-0.016825,-0.010289,0.025451,-0.025237,1.170297,1.284790,1.320702,61.335874,63.050337,55.869999,52.109425,55.997357,59.217447,54.62605,60.611331,65.351953
2070,2018-05-11,55.970001,56.099998,55.959999,56.099998,56.099998,5237.0,0.004117,0.008233,0.012350,-0.000179,0.002323,-0.002317,-0.000357,0.004645,-0.004634,-0.000536,0.006968,-0.006952,1.175115,1.295368,1.337013,61.840874,63.829012,56.099998,52.147825,56.060831,59.287232,54.63115,60.589462,65.261117
2071,2018-05-14,56.480000,56.540001,56.160000,56.349998,56.349998,21697.0,0.004456,0.008913,0.013369,-0.005666,0.001062,0.002307,-0.011331,0.002125,0.004614,-0.016997,0.003187,0.006921,1.180352,1.306913,1.354888,62.392041,64.682341,56.349998,52.187375,56.126830,59.360910,54.64185,60.580216,65.190968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3558,2024-03-18,169.979996,172.720001,169.539993,172.039993,172.039993,19309.0,0.020645,0.041291,0.061936,-0.002589,0.016120,-0.011974,-0.005177,0.032239,-0.023948,-0.007766,0.048359,-0.035922,3.603686,5.798865,3.929578,276.837847,187.598046,172.039993,139.114700,185.551022,106.657993,147.88820,208.179340,125.381982
3559,2024-03-19,171.360001,172.380005,170.039993,172.380005,172.380005,6620.0,0.001976,0.003953,0.005929,-0.007703,0.005952,-0.005917,-0.015406,0.011905,-0.011834,-0.023109,0.017857,-0.017752,3.610808,5.821787,3.952876,277.932106,188.710327,172.380005,139.350600,186.184196,107.204115,148.40640,209.575960,126.589316
3560,2024-03-20,173.020004,173.960007,173.000000,173.300003,173.300003,2882.0,0.005337,0.010674,0.016011,-0.000116,0.005433,-0.001616,-0.000231,0.010866,-0.003231,-0.000347,0.016299,-0.004847,3.630080,5.883929,4.016166,280.898772,191.731787,173.300003,139.591800,186.831504,107.762577,148.95540,211.046051,127.853490
3561,2024-03-21,177.320007,178.919998,176.600006,178.660004,178.660004,6407.0,0.030929,0.061858,0.092787,-0.004060,0.009023,-0.007500,-0.008121,0.018046,-0.015001,-0.012181,0.027070,-0.022501,3.742354,6.247897,4.388815,298.274626,209.522022,178.660004,139.831700,187.479532,108.325165,149.52820,212.578351,129.171104
3562,2024-03-22,178.339996,178.839996,177.539993,177.639999,177.639999,6622.0,-0.005709,-0.011418,-0.017128,-0.004486,0.002804,0.003941,-0.008972,0.005607,0.007881,-0.013457,0.008411,0.011822,3.720989,6.176556,4.313645,294.868809,205.933415,177.639999,140.095100,188.206472,108.970447,150.15360,214.282209,130.665069

In [6]:
# visual
import plotly.express as px
import chart_studio.plotly as py
import plotly.graph_objects as go

fig = px.line(df, x="Date", y=[
    "adj_close_3x",
    "mavg_100_adj_close_3x",
    "mavg_200_adj_close_3x"
])
fig.write_html('figures/first_figure2.html', auto_open=True)

In [43]:
"""
Investment Strategy: Sell when Low is below mavg, buy when High is above mavg. Buy and Sell at mavg price --- 1x
"""

df = df.dropna(axis=0)

def apply_strategy(df, leverage, start_amount, ter, tax=0.25*0.7, transaction_cost=1, spread=0.03):
    operations = ["buy"]
    operations_balance = [start_amount]
    balance = []
    buys = {"buy": [], "index": []}
    sells = {"sell": [], "index": []}
    adj_close = df[f"adj_close_{leverage}x"].to_list()
    mavg = df[f"mavg_200_adj_close_{leverage}x"].to_list()
    returns = df[f"daily_movement_{leverage}x"].to_list()
    open_to_low = df[f"open_to_low_{leverage}x"].to_list()
    open_to_high = df[f"open_to_high_{leverage}x"].to_list()
    adj_close_to_open = df[f"adj_close_to_open_{leverage}x"].to_list()
    lows = df["Low"].to_list()
    highs = df["High"].to_list()
    opens = df["Open"].to_list()
    
    for i in range(len(adj_close)):
        # calculate open, low and high
        #open = adj_close[i] * (1 + adj_close_to_open[i])
        #low = open * (1 + open_to_low[i])
        #high = open * (1 + open_to_high[i])
        open = opens[i]
        low = lows[i]
        high = highs[i]
        
        # claculate return for the day if in the market
        if operations[-1] == "buy":
            # if low below mavg, only calculate loss from open to mavg
            if low < mavg[i]:
                start_amount = start_amount * (1 + returns[i]*1)
            else:
                start_amount = start_amount * (1 + returns[i])

        #print("high:", high, "low:", low, "adj close:", adj_close[i], "mavg:", mavg[i], "balance:", start_amount)

        # buy, if not in the market and adj close price rises above avg
        if high > mavg[i] and operations[-1] != "buy":
            #print(adj_close[i]/mavg[i]-1, ",", sep="")
            operations.append("buy")
            start_amount = start_amount * (1 + returns[i]*1)
            # capture buy price
            operations_balance.append(mavg[i])
            # transaction_cost
            start_amount = start_amount - transaction_cost
            # save buy
            buys["buy"].append(adj_close[i])
            buys["index"].append(i)
        # sell, if in the maket and dj close price falls below avg
        elif low < mavg[i] * 0.6 and operations[-1] != "sell":
            #print(adj_close[i]/(mavg[i]*0.8)-1, ",", sep="")
            operations.append("sell")
            #start_amount = start_amount / (1 + returns[i]) * (adj_close[i] < mavg[i])
            # tax
            if start_amount > operations_balance[-1]:
                start_amount = start_amount - (start_amount - operations_balance[-1]) * tax
            # spread
            start_amount = start_amount * (1 - spread)
            # transaction_cost
            start_amount = start_amount - transaction_cost
            # save sell
            sells["sell"].append(adj_close[i])
            sells["index"].append(i)

        # TER
        if i % 200 == 0:
            start_amount = start_amount * (1 - ter)

        balance.append(start_amount)

    print("-----------------------")
    print(len(operations))
    print(start_amount)
    return balance, buys, sells
        
#amount = df["adj_close_1x"].to_list()[0]
df_base_tail = df_base.tail(len(df))
amount = df_base_tail["Adj Close"].to_list()[0]
print(amount)
balance_200, _, sells = apply_strategy(df=df, leverage=1, start_amount=amount, ter=0.0075)

comp = pd.DataFrame({"avg 200": balance_200})
comp = comp.reset_index()
comp["date"] = df["Date"].to_list()
comp["mavg_200_adj_close_1x"] = df["mavg_200_adj_close_1x"].to_list() #/ df["adj_close_3x"].to_list()[0] * amount
comp["mavg_200_adj_close_1x_factor"] = df["mavg_200_adj_close_1x"] / df["adj_close_3x"].to_list()[0] * amount
#comp["adj_close_3x"] = df["adj_close_3x"].to_list()
comp["adj_close_1x"] = df["adj_close_1x"].to_list()
comp["base"] = df_base_tail["Adj Close"].to_list()
comp = comp.reset_index()

fig = px.line(comp, x="index", y=["avg 200", "adj_close_1x", "mavg_200_adj_close_1x", "mavg_200_adj_close_1x_factor", "base"])
fig = fig.add_scatter(x=_["index"], y=_["buy"], mode="markers")
fig = fig.add_scatter(x=sells["index"], y=sells["sell"], mode="markers")
fig.update_traces(marker=dict(size=10))
fig.write_html('figures/first_figure4.html', auto_open=True)

print(balance_200[-1]/ balance_200[0])
print(pow(balance_200[-1]/balance_200[0], 1/30))

comp.astype(str)


#23 41

2612.620117
-----------------------
3
5447.7135343031905
2.1012984275632633
1.0250607185203267

,level_0,index,avg 200,date,mavg_200_adj_close_1x,mavg_200_adj_close_1x_factor,adj_close_1x,base
0,0,0,2592.5463336593,2018-05-08,52.04567505000001,nan,54.119999000000064,2612.620117
1,1,1,2610.2708336374494,2018-05-09,52.07757503500001,nan,54.49000200000006,2605.0
2,2,2,2676.377748436373,2018-05-10,52.10942505000001,nan,55.869999000000064,2640.870117
3,3,3,2687.3955436176943,2018-05-11,52.14782505000001,nan,56.09999800000006,2581.879883
4,4,4,2699.371460014419,2018-05-14,52.18737504500001,nan,56.34999800000006,2614.449951
...,...,...,...,...,...,...,...,...
1491,1491,1491,5275.977277547307,2024-03-18,139.11470011999992,nan,172.03999299999992,5096.27002
1492,1492,1492,5286.404478541748,2024-03-19,139.35060007999994,nan,172.38000499999993,5137.080078
1493,1493,1493,5314.618200588278,2024-03-20,139.59180010999992,nan,173.30000299999992,5130.950195
1494,1494,1494,5478.994186604686,2024-03-21,139.83170012499994,nan,178.6600039999999,5078.649902
1495,1495,1495,5447.7135343031905,2024-03-22,140.09510012999993,nan,177.6399989999999,5104.759766

In [17]:
"""
Investment Strategy: Sell when Low is below mavg, buy when High is above mavg. Buy and Sell at mavg price
"""

df = df.dropna(axis=0)

def apply_strategy(df, leverage, start_amount, ter, tax=0.25*0.7, transaction_cost=1, spread=0.02):
    operations = ["buy"]
    operations_balance = [start_amount]
    balance = []
    buys = {"buy": [], "index": []}
    sells = {"sell": [], "index": []}
    adj_close = df[f"adj_close_{leverage}x"].to_list()
    mavg = df[f"mavg_200_adj_close_{leverage}x"].to_list()
    returns = df[f"daily_movement_{leverage}x"].to_list()
    open_to_low = df[f"open_to_low_{leverage}x"].to_list()
    open_to_high = df[f"open_to_high_{leverage}x"].to_list()
    adj_close_to_open = df[f"adj_close_to_open_{leverage}x"].to_list()
    
    for i in range(len(adj_close)):
        # calculate open, low and high
        open = adj_close[i] * (1 + adj_close_to_open[i])
        low = open * (1 + open_to_low[i])
        high = open * (1 + open_to_high[i])
        
        # claculate return for the day if in the market
        if operations[-1] == "buy":
            # if low below mavg, only calculate loss from open to mavg
            if low < mavg[i]:
                start_amount = start_amount * (1 + returns[i]*1)
            else:
                start_amount = start_amount * (1 + returns[i])

        #print("high:", high, "low:", low, "adj close:", adj_close[i], "mavg:", mavg[i], "balance:", start_amount)

        # buy, if not in the market and adj close price rises above avg
        if high > mavg[i] and operations[-1] != "buy":
            #print(adj_close[i]/mavg[i]-1, ",", sep="")
            operations.append("buy")
            start_amount = start_amount * (1 + returns[i]*1)
            # capture buy price
            operations_balance.append(mavg[i])
            # transaction_cost
            start_amount = start_amount - transaction_cost
            # save buy
            buys["buy"].append(adj_close[i])
            buys["index"].append(i)
        # sell, if in the maket and dj close price falls below avg
        elif low < mavg[i] * 0.8 and operations[-1] != "sell":
            #print(adj_close[i]/(mavg[i]*0.8)-1, ",", sep="")
            operations.append("sell")
            #start_amount = start_amount / (1 + returns[i]) * (adj_close[i] < mavg[i])
            # tax
            if start_amount > operations_balance[-1]:
                start_amount = start_amount - (start_amount - operations_balance[-1]) * tax
            # spread
            start_amount = start_amount * (1 - spread)
            # transaction_cost
            start_amount = start_amount - transaction_cost
            # save sell
            sells["sell"].append(adj_close[i])
            sells["index"].append(i)

        # TER
        if i % 200 == 0:
            start_amount = start_amount * (1 - ter)

        balance.append(start_amount)

    print("-----------------------")
    print(len(operations))
    print(start_amount)
    return balance, buys, sells
        
amount = df["adj_close_1x"].to_list()[0]
balance_200, _, sells = apply_strategy(df=df, leverage=3, start_amount=amount, ter=0.0075)

comp = pd.DataFrame({"avg 200": balance_200})
comp = comp.reset_index()
comp["date"] = df["Date"].to_list()
comp["mavg_200_adj_close_3x"] = df["mavg_200_adj_close_3x"].to_list() #/ df["adj_close_3x"].to_list()[0] * amount
comp["mavg_200_adj_close_3x"] = comp["mavg_200_adj_close_3x"] / df["adj_close_3x"].to_list()[0] * amount
comp["adj_close_3x"] = df["adj_close_3x"].to_list()
comp["adj_close_1x"] = df["adj_close_1x"].to_list()
comp = comp.reset_index()

fig = px.line(comp, x="index", y=["avg 200", "mavg_200_adj_close_3x", "adj_close_3x", "adj_close_1x"])
fig = fig.add_scatter(x=_["index"], y=_["buy"], mode="markers")
fig = fig.add_scatter(x=sells["index"], y=sells["sell"], mode="markers")
fig.update_traces(marker=dict(size=10))
fig.write_html('figures/first_figure4.html', auto_open=True)

print(balance_200[-1]/ balance_200[0])
print(pow(balance_200[-1]/balance_200[0], 1/30))

comp.astype(str)


#1900 3300

-----------------------
7
5848.940357614968
3.001342851837024
1.0373146710569614

,level_0,index,avg 200,date,mavg_200_adj_close_3x,adj_close_3x,adj_close_1x
0,0,0,1948.7744807411864,2017-07-31,1600.2955223843016,2581.939860044986,1961.0999760000018
1,1,1,1976.4992725935142,2017-08-01,1603.64374872961,2618.6725584164,1970.4000240000016
2,2,2,1976.1984191946551,2017-08-02,1607.1861636061517,2618.273956428217,1970.3000490000018
3,3,3,1971.3837548397091,2017-08-03,1610.793904116692,2611.894986499359,1968.6999510000019
4,4,4,1968.6803685016637,2017-08-04,1614.3312961753304,2608.3132580786105,1967.8000490000015
...,...,...,...,...,...,...,...
1654,1654,1654,5774.923912061946,2024-02-28,4019.939953790773,7070.048767043718,3322.600098000008
1655,1655,1655,5851.050774502936,2024-02-29,4029.9436613917956,7163.248372464606,3337.1999510000082
1656,1656,1656,5992.0148609471835,2024-03-01,4040.607832752865,7335.826051536874,3364.0000000000086
1657,1657,1657,5982.930914762687,2024-03-04,4051.5998434928642,7324.704876002865,3362.3000490000086
1658,1658,1658,5848.940357614968,2024-03-05,4062.2051988951275,7160.664658714618,3337.1999510000087

In [65]:
buy = [0.01902456140658937,
0.023921858855936007,
-0.009610158513005396,
0.023619477868030092,
0.0023717611005305006,
-0.04523143484391223,
0.013761359695142472,
-0.01780350728578295,
0.004124804866382004,
-0.0004893179161492567,
-0.0050990860030094565,
-0.08350118995494071,
0.0020846373306246946,
0.0020350175378183177,
0.009567519063300667]

sell = [-0.13289314875135405,
0.049690210669110835,
0.0026513025059928808,
0.002534877679760017,
0.023469621584752298,
0.10011032871439829,
-0.030846949733219442,
-0.019121919214916017,
-0.07828236785774023,
0.007905865241265797,
0.05297711300821262,
0.10058843633334047,
-0.1524216436239918,
0.07490512064452015,
0.04229404306215345,]

from statistics import mean
print(mean(buy))
print(mean(sell))

-0.004081579786163058
0.002904059350819018